# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://docs.allenstech.io
#baseurl: "/blog"
timezone: America/New_York
title: Allenstech Blog
subtitle: "Tech tutorials and news"
description: "This site serves as my personal blogging and tech news hub."
repository: "Allenstech-Homelab/allenstechio.github.io"
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      search: true
      read_time: true
      enable_copy_code_button: true
      show_date: true
      share: true
      related: true

author:
  name     : "Michael Allen"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "IT infrastructure professional with years of experience and certifications including AZ-104, AZ-305, VMware VCP-DCV 2022, CySA+, and Security+. Passionate about sharing knowledge in the tech space."
  location : "Georgia, USA"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/michaeljallen941"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/allenstechio"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/allenstech_io"
    - label: "Credly"
      icon: "fab fa-fw fa-file-certificate"
      url: "https://www.credly.com/users/john-michael-allen"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jmichael.allen/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
